language: node_js
sudo: false
dist: trusty
node_js: '9'
addons:
  firefox: latest
  chrome: stable
  sauce_connect: true
cache:
  directories:
  - node_modules
env:
  global:
  - 
  - secure: mRVq6Gjuq8QOakh9llctKR615PMnKB6HUkLEpZFNHMSXSJryLsZFUAYS5d9TRVtgiaExMciOWQAuAly/08TwLcob1aDPPzs6e2cZK18lRny4o0O3Ax4Kp6cdE27RP2xVIbqyodsYgHbvbAC/3bCWCBWC89LRBL2hEiZZ2fyMu7a2PECH/S1A33D/x1gzzXlvuroMvfbTrPenV3Ps/ZL7R27EHjB6I8ktMUvULXeyI3jmsRtAiqfd6N70caW0mFJsl6Y6A9hWNd2AjdIPxbiLESpbSBFnOdixLwAs5RLudLLQz+so1i/tOuZldXs+iDHVB+iHRl2nj6WY+nbXEObePFhk3S7wA9c4SKNY9tfOzT/FYn96QZdSdVyqQnhyj67YqejF7wSLD4YNfp2llyDBHQAdVd4Z7y/qlsLxgPzdponzlKzecSfjl9Q7wDdWEpPQtQfwjd1nZ/eeGmFwHTlKUfcAkkNOvNteJGabJBXpgoNljHRuevBLsZyZnTw+NPGVnhBdOw7mrWE4vMt5wH64PIFJmJWrWTiyzgOXuP1lh3LirQvWYK4tvmeQvLWosESqz5c+DE5x382fjIHUmIflxOnBYMwTjx8OCbkrhN3kb2NFNz3MyBD9Dz+yYRmzPaUU10HNKlFf1U3bT/c/IUTTkY+VxXKtwPfmOfSJTpMhbvk=
  - secure: gHKVw3rluT5gBkkUALh9Rh8fYmtolE2TNBSOvblWI9JZuyHFKMTiyaL9BZJ98Yrr9mrlHcbOe3d+GwNs6wt+zLD3Bbqy8s3gqtOhNUBYXM/OcIcmrbnVSqnRCaxzckWsNKpYWG1q0fnbcBCv6AU+sDGT72JKigPqSPhfLUQBMgr3RVND1QW8ujcjdSE8NAa8OfKvigwNZjC1svOuRZTXae+E5smSWXx0BAZ2BTM9DbWEkOZXcaIRXUZL2PMuk01zxX9M/P5k7JUbRkR3VAlx6b9lL2dsjqawREBRu3pQ+3QX5V7fat/ach174zNjKcmiqzCjk+3jnPAbeXhxybYJmf/FDMuwU9/nuUDAyzetgZ4p5mDgL89XiDK6TijW16UwPE2djkMarFXoaGWp7VHsQ7rNWdp7fGcmSmvvRwJrQuDO3RgnBM3m+vqOw03vKQzeDCsUCgYXut+An5b6Tzya2X1rYPH6QuprRNySctCXvlz+ENyG/SPY7zirK9irc/MIMzEJb27jYgcdTSOwFIXfL48CHQj7kPtB05wPIhpElJnA5uKmavhH3zMJCDiBn8rRSCwwwSsivuQhFKbga80G/VCQBxvOs1il8JcqQU8JinlfFVGHn9Gji13gvIk3jIxPo+ZSOd4OCVMf4D0NrMBYzTVCFPyf/9bb7M+ii7Qt1ZE=
  - secure: NXCo0PeZN8E5dzDyVEr5rINiwIfP7uIdXkjeCcmNo9RtwAsWSw3fohtvjP5ugLD8ADIIcYBH+WvrLGBoeDRlVswCaZDT9ee9uAABKmmMYjbM/hNzKxvX6hLXlnuNHojFJNQL+zym854MTyWoAP44vrikYomeMEmC1mL/N8mJp0FT6T/Lvzut7cMN2UlN6wKqcmee9b+bkv1Jqhw6gRukYw9LIC36rQEV7q6hrdVwjkLK81rCjSQHhpZiXXBqEUJF3Y5iSBg702FWZw0YF84C5xu8NNSBomADNQpqbe4y0frAAG1jsPmIBgDP0fCnjEVPiOj4zWmCs48KpD9ECDpKS3Iiyd2LpOWY89Y6WGRC4w06CUV7oPYjYbxBsw6dPoibwFzvia9q2yLFNvcYIIAFglcfcsyHK/SLh7uu7Qw8kv8WszibDRNFCm0UDlzsLY/gfxV07iQNuPSDvPw55E1yC852iJE5YuayouaugFb6h83laef1kA9nEt4HpCaC8RUKeDE8EIWe4sv+3Ltdlyfs3ZBo9yBaXwiHd1Q5dy3euUhsNhvMyWzZnUaHUVdAtgyBKrlu8aY1f0mmavUT1BnC/vFGbnTRMcG0ZaxKz+dlt4go/7/68Rn5zGbi7XqM7zmpr9GCpiGfnU5oyA+BhB5Tb8K0ueUSUuIX0DNeE1qRaX8=
  - secure: MkiSrUZESaUrtjBlQQcfRELhCCuzodXgvFoZLju24TbiBnjAgeHegu6UxIMosa7oqiaHKFU/N3O0lOzCz/GqLXCNF+pL6fgsMTsYCvt1j7DLTFriWvUzf5odpUms3KeObFRPZM+438aX2r8UFoBVZzknpebxMq/Tuv1uokliJv7fo6wuIc0+wbI2stj4gkkwWl8Aj0gZ3ZwoAZ7UBfBNiXXn2fzfalYJrASEy+23Rd5Kd7uDKPhrnLA0AdH48fNy1KCmaiM9hB5u9PdZrVDyRrtyuCq8Azm8u6xSRuSnYBYV8vciazWhAyckRntwn1lgJTKE6HwCDaMdXbgt1AgsofDldekC45nLLZOOQ2nZ84IjOsphRSTXBCR+baVaDq2Ed97ZpbstR7KZsR69EBLVgF4krCPBLKMXRfjXy8yFI4sv/5bt0Q0c/JnSLDtRb91d6NpBQDabcW9Tf4GxMJlX3soN4irjGlXS7YNa/tKeHGbxPPjUlav2p2Aoz9lpIv3swacQnMOaedjURRpcxse1vG1maNSLkTKSpjeWaaUpwWPnqdqQ4r+XKpLRgJNE4naTGOrAhGrH5/eNX9wm/KPZKEOQnzjIlAblEfAn6v/e+AFgwL2l/GtpENN49zoGGQ4qb5JT5CyOV+cGG5hH1HAqu3iZa7DITdq6pIXY3FDiDGA=
matrix:
  fast_finish: true
  allow_failures:
  - env: JOB=benchmark
  include:
  - env: JOB=test KARMA_BROWSERS="Chrome,Firefox" KARMA_CUSTOM_LAUNCHERS="./test/custom-launchers-browserstack.json"
    before_script: npm run lint
    script: xvfb-run time npm test
  - env: JOB=benchmark
    script: "./travis-bench.sh"
